accounts: {
    SYS: {
        users: [
            {user: admin, password: password}
        ]
    }
}

system_account: SYS


cluster: {
    name: Tashkent,
    port: 6222,
    routes: [
        "nats://tash-1:6222",
        "nats://tash-2:6222",
        "nats://tash-3:6222"
    ]
}